### ISSUE TITLE
Feature:  All changes . Not just tailing 

### ISSUE THREAD

**Issue by gedw99** [ConduitIO/conduit-connector-file#46]
### Feature description

Allow any change in the whole file to be detexted and so be a true cdc source for files.

Should be a new connector type because tailing is for log file patterns and cdc is for other use cases.

This cdc file plugin would be a really good test harness too.

the way if could work is to reuse the watching code but then do a diff calculation using the same logic that git employs. Git produces a patch that can be converted to match the conduits cdc protocol.

**Comment by gedw99** [comment]
Would you take a PR that does all file changes ? It will be a basic poller ( so it works everywhere ) .

Each change will conform to the cdc protocol .. 

The idea is to know exactly what line changed and the nature of the change. Just like a row change in a db basically .

Or if you want it can be a new type of connector .. 

Anyways let me know :)

**Comment by gedw99** [comment]
I totally agree with you both - new connector. It has totally different semantics / behaviours.

The unified diff code is a good place to start and then work backwards ? Cause do we want it to work with the conduit  protocol like all Connectors ?  

I have spent enough time deep diving Conduit to know

**Comment by simonl2002** [comment]
@gedw99 yes, we'd want it to work with the conduit protocol like any other connector.
I'd start with the (Building Connectors)[https://conduit.io/docs/connectors/building] and learning about the (connector lifecycle)[https://conduit.io/docs/connectors/connector-lifecycle]

When you're ready to build you can use the (Conduit Connector SDK)[https://github.com/conduitio/conduit-connector-sdk]

**Comment by gedw99** [comment]
@simonl2002 got it 

will digest those links
